In [12]:
import numpy as np
uretim = np.array([45, 60, 20, 80, 35, 100, 85, 40, 55, 65, 30, 90, 45, 75, 20, 85, 95, 40, 70, 60, 50, 80, 35, 95, 25, 110, 80, 45, 70, 60])
kisi_uretim = uretim.reshape(3,10)
gun_uretim = uretim.reshape(10,3)
kisi_toplam = np.sum(kisi_uretim, axis=1)
gun_ort = np.mean(kisi_uretim, axis=0)
ayin_elemani_index = np.argmax(kisi_toplam)
isimler = ["Ali", "Veli", "Ayşe"]
ort = np.mean(kisi_uretim)
kisi_uretim[kisi_uretim < ort] = ort
basari_gun = np.sum(gun_uretim >= 90)
print("--- FABRİKA ANALİZ RAPORU ---\n\n\n")
print(f"İşçi Toplam Üretimleri: Ali={kisi_toplam[0]}, Veli={kisi_toplam[1]}, Ayşe={kisi_toplam[2]}\n")
print(f"Ayın Elemanı: {isimler[ayin_elemani_index]}!\n")
print(f"90 ve üzeri üretim yapılan gün sayısı: {basari_gun}\n")
print(f"Genel Fabrika Ortalaması: {ort:.2f}\n")
print("\nGüncellenmiş Üretim Tablosu:\n", kisi_uretim)

--- FABRİKA ANALİZ RAPORU ---



İşçi Toplam Üretimleri: Ali=585, Veli=610, Ayşe=650

Ayın Elemanı: Ayşe!

90 ve üzeri üretim yapılan gün sayısı: 5

Genel Fabrika Ortalaması: 61.50


Güncellenmiş Üretim Tablosu:
 [[ 61  61  61  80  61 100  85  61  61  65]
 [ 61  90  61  75  61  85  95  61  70  61]
 [ 61  80  61  95  61 110  80  61  70  61]]
