In [1]:
import numpy as np

satislar = np.array([10, 15, 20, 10, 5, 30, 40, 12, 18, 25, 10, 8, 35, 50])
haftalik  = satislar.reshape(2,7)
haftatop = np.sum(haftalik, axis=1)
gunort = np.mean(haftalik, axis=0)
iyisatsay = np.sum(haftalik > 20)
print("Haftalık bilanço: \n", haftalik)
print("Haftalık toplam: ", haftatop)
print("Günlerin Ortalaması: ", gunort)
print("Yüksek Satış Yapılan Gün Sayısı: ", iyisatsay)

print("\n\n 1. Haftanın Hafta Sonu:", haftalik[0, 5:])
print("Çarşambalar:", haftalik[:, 2])
print("Son Pazar:", haftalik[1, -1])
haftalik[1,-1] = 100
print("\n Oops pardon gerçek Son Pazar:", haftalik[1, -1])
print("\n\n") 

rekor_satislar = haftalik[haftalik > 30]
ortalama1 = np.mean(haftalik)
haftalik[haftalik < ortalama1] = 0
print(haftalik)
print(rekor_satislar)



Haftalık bilanço: 
 [[10 15 20 10  5 30 40]
 [12 18 25 10  8 35 50]]
Haftalık toplam:  [130 158]
Günlerin Ortalaması:  [11.  16.5 22.5 10.   6.5 32.5 45. ]
Yüksek Satış Yapılan Gün Sayısı:  5


 1. Haftanın Hafta Sonu: [30 40]
Çarşambalar: [20 25]
Son Pazar: 50

 Oops pardon gerçek Son Pazar: 100



[[  0   0   0   0   0  30  40]
 [  0   0  25   0   0  35 100]]
[ 40  35 100]
